services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   networks:
  #     - default
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - db
  #   command: ["npm", "start"]  # Comando para iniciar la app (ajusta según tu configuración)

 db:
    image: mysql:8.0
    container_name: trading-db
    restart: always
    ports:
      - "3310:3306"  # Exponiendo el puerto 3306 de MySQL en el host como 3310
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: trading
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d  # Monta el directorio con el script .sql para la inicialización
    networks:
      - default
    command: --default-authentication-plugin=mysql_native_password  # Configuración para compatibilidad con clientes antiguos

volumes:
  db_data:

networks:
  default:
    driver: bridge

